const rules = {
  'array-callback-return': 1,
  'brace-style': [1, 'stroustrup'],
  camelcase: 1,
  'getter-return': 1,
  eqeqeq: [1, 'smart'],
  'no-async-promise-executor': 1,
  'no-cond-assign': [1, 'except-parens'],
  'no-caller': 2,
  'no-control-regex': 1,
  'no-console': 1,
  'no-debugger': 1,
  'no-dupe-args': 2,
  'no-dupe-class-members': 1,
  'no-dupe-keys': 2,
  'no-duplicate-case': 2,
  'no-duplicate-imports': 1,
  'no-empty': [1, { allowEmptyCatch: true }],
  'no-eval': 2,
  'no-ex-assign': 1,
  'no-extend-native': 1,
  'no-extra-bind': 1,
  'no-extra-label': 1,
  'no-extra-boolean-cast': 1,
  'no-func-assign': 2,
  'no-global-assign': 2,
  'no-implied-eval': 1,
  'no-invalid-regexp': 1,
  'no-label-var': 1,
  'no-labels': [1, { allowLoop: true, allowSwitch: false }],
  'no-lone-blocks': 1,
  'no-loop-func': 1,
  'no-self-compare': 1,
  'no-use-before-define': 1,
  'no-mixed-operators': [
    1,
    {
      groups: [
        ['&', '|', '^', '~', '<<', '>>', '>>>'],
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: false,
    },
  ],
  'no-unsafe-negation': 1,
  'no-new-func': 1,
  'no-new-object': 1,
  'no-octal': 1,
  'no-redeclare': 2,
  'no-script-url': 1,
  'no-self-assign': 1,
  'no-self-compare': 1,
  'no-sequences': 1,
  'no-this-before-super': 1,
  'no-undef': 2,
  'no-unreachable': 1,
  'no-unused-expressions': [
    1,
    {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: true,
    },
  ],
  'no-unused-labels': 1,
  'no-unused-vars': [
    1,
    {
      args: 'none',
      ignoreRestSiblings: true,
    },
  ],
  'no-use-before-define': [
    1,
    { classes: false, functions: false, variables: false },
  ],
  'no-useless-computed-key': 1,
  'no-useless-concat': 1,
  'no-useless-constructor': 1,
  'no-useless-escape': 1,
  'no-useless-rename': [
    1,
    {
      ignoreDestructuring: false,
      ignoreImport: false,
      ignoreExport: false,
    },
  ],
  'require-yield': 1,
  'use-isnan': 1,
  'valid-typeof': 1,
  'prefer-const': 1,

  'simple-import-sort/imports': 2,
  'simple-import-sort/exports': 2,

  'import/first': 2,
  'import/no-amd': 2,
  'import/no-webpack-loader-syntax': 2,
};

module.exports = rules;
