const rules = {
  "jest/no-conditional-expect": 1,
  "jest/no-deprecated-functions": 1,
  "jest/no-disabled-tests": 1,
  "jest/no-export": 2,
  "jest/no-focused-tests": 1,
  "jest/no-identical-title": 1,
  "jest/no-interpolation-in-snapshots": 1,
  "jest/no-jasmine-globals": 2,
  "jest/no-jest-import": 1,
  "jest/no-mocks-import": 1,
  "jest/valid-describe-callback": 2,
  "jest/valid-expect": 2,
  "jest/valid-expect-in-promise": 2,

  "jest-dom/prefer-checked": 1,
  "jest-dom/prefer-empty": 1,
  "jest-dom/prefer-enabled-disabled": 1,
  "jest-dom/prefer-focus": 1,
  "jest-dom/prefer-in-document": 1,
  "jest-dom/prefer-required": 1,
  "jest-dom/prefer-to-have-attribute": 1,
  "jest-dom/prefer-to-have-class": 1,
  "jest-dom/prefer-to-have-style": 1,
  "jest-dom/prefer-to-have-text-content": 1,
  "jest-dom/prefer-to-have-value": 1,

  "testing-library/await-async-query": 2,
  "testing-library/await-async-utils": 2,
  "testing-library/no-await-sync-events": 2,
  "testing-library/no-await-sync-query": 2,
  "testing-library/no-debugging-utils": 1,
  "testing-library/no-promise-in-fire-event": 2,
  "testing-library/no-render-in-setup": 2,
  "testing-library/no-unnecessary-act": 2,
  "testing-library/no-wait-for-empty-callback": 2,
  "testing-library/no-wait-for-multiple-assertions": 2,
  "testing-library/no-wait-for-side-effects": 2,
  "testing-library/no-wait-for-snapshot": 2,
  "testing-library/prefer-find-by": 1,
  "testing-library/prefer-presence-queries": 1,
  "testing-library/prefer-query-by-disappearance": 1,
  "testing-library/prefer-screen-queries": 1,
  "testing-library/prefer-user-event": 1,
  "testing-library/prefer-wait-for": 1,
  "testing-library/render-result-naming-convention": 1,
};

module.exports = rules;
